### ISSUE TITLE
.drone.yml:127-131: Fill drone-sided app with data. Do...

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#534]
The puzzle `517-a10609a6` from #517 has to be resolved:

https://github.com/fidals/shopelectro/blob/ee7eda07bb39f7cb99b7eebbaef732f261c526e7/.drone.yml#L127-L131

The puzzle was created by duker33 on 22-Aug-18. 

Estimate: 60 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by artemiy312** [comment]
Seems #517 is unresolved, because `docker-compose up -d` is still [failed](https://ci.fidals.com/fidals/shopelectro/747/4)

**Comment by artemiy312** [comment]
We have faced with another one [issue](https://ci.fidals.com/fidals/shopelectro/760/5), postgres does not work and it seems because of running docker instance in docker.

**Comment by duker33** [comment]
> Seems #517 is unresolved, because docker-compose up -d is still failed

@artemiy312 , it worked before merge: https://ci.fidals.com/fidals/shopelectro/732
`DJANGO_SETTINGS_MODULE=shopelectro.settings.drone` for app-drone service should resolve it.
You resolved it already, as i see.

> We have faced with another one issue, postgres does not work and it seems because of running docker instance in docker.

@artemiy312 , just comment volumes in `postgres` service for a while. It's because of them, i think

**Comment by artemiy312** [comment]
@duker33 Let's clarify, what kind of problem docker-up pipeline will solve for us? Seems we already satisfy [requirements of a parent issue](https://github.com/fidals/shopelectro/issues/396), because we already build and use docker images for test, isn't it?

But if we want also to test working of docker-compose.yml, then drone can not help us with it, because we have to create mock configs for it, these do not look helpful
The best way to do it, as I believe, will be deploying of stage with new coming changes after merging of a PR or new release.
 
[drone would](http://plugins.drone.io/appleboy/drone-ssh/) help with such deploys 

What do think?

**Comment by duker33** [comment]
> after merging of a PR or new release

@artemiy312 , it's too late to test code diff, i afraid. But it's better than nothing.
Let's do this. New stage task will be blocked by https://github.com/fidals/stroyprombeton/issues/232

**Comment by duker33** [comment]
@artemiy312 , create plz pdd sub-issues and close it

**Comment by artemiy312** [comment]
I changed the estimate, because I am going to resolve an issue with the order of container startups

**Comment by 0pdd** [comment]
@0pdd the puzzle [#587](https://github.com/fidals/shopelectro/issues/587) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#587](https://github.com/fidals/shopelectro/issues/587) is solved here.
