### ISSUE TITLE
Reuse refarm's get_category_path helper in tests

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#637]
From https://github.com/fidals/stroyprombeton/issues/344

It's required to remove code doubling

**Comment by artemiy312** [comment]
`get_category_path` function is not suitable for SE, because the function doesn't handle neither slugs as identifiers nor `offset` url kwargs, but these are required for SE.

Redesign of the function probably will produce terrible interface. I believe we shouldn't reuse the `get_category_path`. @duker33 , what do you think?

**Comment by duker33** [comment]
@artemiy312 , we should not `slug` instead of `id` in stb urls.
With this approach we can unify urls and this function too.

Offset is not big problem, i think. It'll have some default value, that does not affect urls

**Comment by artemiy312** [comment]
@duker33 you already [have faced with the issue](https://github.com/fidals/refarm-site/pull/226#pullrequestreview-186044100), so maybe you want to take it?
