### ISSUE TITLE
models.py:74-75: Add MatrixBlock to the admin panel....

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#934]
The puzzle `880-c9d8b5dc` from #880 has to be resolved: 

https://github.com/fidals/shopelectro/blob/6ed077725bf1891cd003097b5acaab3220274046/shopelectro/models.py#L74-L75

The puzzle was created by Artemiy on 04-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by artemiy312** [comment]
>Inline it on Category Edit page. 

Django can't inline `MatrixBlock -> Category -> CategoryPage` relation into `CategoryPageAdmin`. We could use [nested-inline package](https://github.com/s-block/django-nested-inline) or change relation from `category` to `page` to reduce the nesting level.

But it seems for me it doesn't have a sense to inline `MatrixBlock` to `CategoryPage`, because not every page has a `MatrixBlock`. I'd said only several pages have them.

So creation of separate admin model instead more appropriate. 

@duker33 What do you think? Will be OK just create a separate admin model?

**Comment by artemiy312** [comment]
It'll look so:

<img width="941" alt="изображение" src="https://user-images.githubusercontent.com/13870342/60724551-6bb08f80-9f3f-11e9-9716-8a8437f387da.png">
<img width="817" alt="изображение" src="https://user-images.githubusercontent.com/13870342/60724569-7834e800-9f3f-11e9-8c3c-99774674ff9e.png">

**Comment by duker33** [comment]
@artemiy312 , let's leave your decision since it's simple. If users will complain we'll think about it

**Comment by 0pdd** [comment]
@0pdd the puzzle [#942](https://github.com/fidals/shopelectro/issues/942) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#942](https://github.com/fidals/shopelectro/issues/942) is solved here.
